apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      chart: traefik
      version: 9.12.3
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 5m0s
  values:
    deployment:
      kind: DaemonSet
    logs:
      general:
        level: DEBUG
    ingressClass:
      enabled: true
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: true
    additionalArguments:
      - "--entrypoints.websecure.http.tls"
      - "--ping"
      - "--api.dashboard=true"
      - "--metrics.prometheus=false"
      - "--providers.kubernetesingress.ingressendpoint.hostname=wintergrasp.icecrown.local"
    ports:
      web:
        redirectTo: websecure
    service:
      externalIPs:
        - 10.10.20.80
      spec:
        externalTrafficPolicy: Local