apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: production-ssl
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: kyle@resolv.sh
    privateKeySecretRef:
      name: production-ssl
    solvers:
    - dns01:
        cloudflare:
          email: kyle@resolv.sh
          apiKeySecretRef:
            name: cloudflare-api
            key: api-key