apiVersion: v1
kind: ConfigMap
metadata:
  ##creationTimestamp: null
  name: metallb-helm-chart-value-overrides
  namespace: metallb-system
data:
  values.yaml: |-
    ## @section Global parameters
    ## Global Docker image parameters
    ## Please, note that this will override the image parameters, including dependencies, configured to use the global value
    ## Current available global Docker image parameters: imageRegistry, imagePullSecrets and storageClass

    ## @param global.imageRegistry Global Docker image registry
    ## @param global.imagePullSecrets Global Docker registry secret names as an array
    ##
    global:
    imageRegistry: ""
    ## E.g.
    ## imagePullSecrets:
    ##   - myRegistryKeySecretName
    <snip>
    prometheus:
        ## Prometheus Operator service monitors
        ##
        serviceMonitor:
        ## @param speaker.prometheus.serviceMonitor.enabled Enable support for Prometheus Operator
        ##
        enabled: false
        ## @param speaker.prometheus.serviceMonitor.jobLabel Job label for scrape target
        ##
        jobLabel: "app.kubernetes.io/name"
        ## @param speaker.prometheus.serviceMonitor.interval Scrape interval. If not set, the Prometheus default scrape interval is used
        ##
        interval: ""
        ## @param speaker.prometheus.serviceMonitor.metricRelabelings Specify additional relabeling of metrics
        ##
        metricRelabelings: []
        ## @param speaker.prometheus.serviceMonitor.relabelings Specify general relabeling
        ##
        relabelings: []
