apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: cluster-info
  namespace: notifications
spec:
  providerRef:
    name: discord-notification
  eventSeverity: info
  eventSources:
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'