apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Alert
metadata:
  name: cluster-error
  namespace: notifications
spec:
  providerRef:
    name: discord
  eventSeverity: error
  eventSources:
    - kind: HelmRelease
      namespace: 'kube-system'
      name: '*'
    - kind: HelmRelease
      namespace: 'flux-system'
      name: '*'
    - kind: HelmRelease
      namespace: 'default'
      name: '*'
    - kind: HelmRelease
      namespace: 'metallb-system'
      name: '*'
    - kind: HelmRelease
      namespace: 'cert-manager'
      name: '*'
    - kind: GitRepository
      name: '*'
    - kind: Kustomization
      name: '*'