apiVersion: notification.toolkit.fluxcd.io/v1beta1
kind: Provider
metadata:
  name: discord-notification
  namespace: notifications
spec:
  type: discord
  username: flux
  channel: cluster
  secretRef:
    name: discord-webhook