apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
spec:
  maxHistory: 3
  interval: 10m0s
  suspend: false
  releaseName: metallb
  chart:
    spec:
      chart: metallb
      version: 2.0.4
      sourceRef:
        kind: HelmRepository
        name: bitnami-charts
        namespace: flux-system
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 10.10.20.80-10.10.20.84
    controller:
      image:
        registry: docker.io
        repository: metallb/controller
        tag: v0.9.5
    speaker:
      image:
        registry: docker.io
        repository: metallb/speaker
        tag: v0.9.5