apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: default
spec:
  dependsOn:
    - name: cert-manager
      namespace: cert-manager
  interval: 5m0s
  chart:
    spec:
      chart: traefik
      version: 9.12.3
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 5m0s
  values:
    deployment:
      kind: DaemonSet
    logs:
      general:
        level: DEBUG
    ingressClass:
      enabled: true
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: true
        insecure: true
    additionalArguments:
      - "--ping"
      - "--api.dashboard=true"
      - "--providers.kubernetesingress.ingressendpoint.hostname=icecrown.online"
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 10.10.20.80
        externalTrafficPolicy: Local
      externalIPs:
        - 10.10.20.80
  web:
    address: :80
  websecure:
    address: :443