apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: default
spec:
  maxHistory: 3
  interval: 5m0s
  suspend: false
  releaseName: traefik
  chart:
    spec:
      chart: traefik
      version: 9.12.3
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  values:
    image:
      repository: traefik
      tag: 2.3.7
      pullPolicy: IfNotPresent
    env:
    - name: TZ
      value: Europe/London
    installCRDs: true
    ingressClass:
      enabled: true
      isDefaultClass: "true"
    ingressRoute:
      dashboard:
        enabled: true
    globalArguments:
    - --global.checknewversion=false
    - --global.sendanonymoususage=false
    - --api.insecure=true
    - --accesslog=true

    ports:
      traefik:
        expose: true
        port: 9000
        protocol: TCP
      web:
        expose: true
        exposedPort: 80
        port: 8000
        protocol: TCP
      websecure:
        expose: true
        exposedPort: 443
        port: 8443
        protocol: TCP
    service:
      enabled: true
      type: LoadBalancer
      spec:
        loadBalancerIP: 10.10.20.80
        externalTrafficPolicy: Local
    dnsPolicy: ClusterFirst
    logs:
      general:
        level: INFO
      access:
        enabled: true
    pilot:
      enabled: false