apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      chart: traefik
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 5m0s
  values:
    deployment:
      enabled: true
      kind: DaemonSet
    ingressClass:
      enabled: true
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: true
    ports:
      web:
        redirectTo: web
    service:
      externalIPs:
        - 10.10.20.80
    logs:
      general:
        level: DEBUG
      access:
        enabled: true
globalArguments:
  - "--global.checknewversion"