apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: default
spec:
  interval: 5m0s
  chart:
    spec:
      chart: traefik
      version: 9.12.3
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
      interval: 5m0s
  values:
    deployment:
      kind: Deployment
    logs:
      general:
        level: DEBUG
      access:
        enabled: true
    ingressClass:
      enabled: true
      isDefaultClass: true
    ingressRoute:
      dashboard:
        enabled: true
        insecure: true
    additionalArguments:
      - "--api.dashboard=true"
      - "--providers.kubernetesingress.ingressendpoint.hostname=icecrown.online"
    service:
      enabled: true
    ports:
      traefik:
        port: 9000
        expose: true
        exposedPort: 9000
        protocol: TCP
      web:
        port: 8000
        expose: true
        exposedPort: 80
        protocol: TCP
      type: LoadBalancer
      spec:
        loadBalancerIP: 10.10.20.80
        externalTrafficPolicy: Local
      externalIPs:
        - 10.10.20.80